# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: biostats

channels:
  - conda-forge

dependencies:
  - python
  - numpy
  - pandas
  - ipykernel
  - seaborn
  - matplotlib
  - scipy
